[package]
name = "blackjack_simulator"
version = "0.1.0"
authors = ["Quentin Kniep <hello@quentinkniep.com>"]
edition = "2018"

[dependencies]
indicatif = "0.15"
prettytable-rs = "0.8"
rand = { version="0.8", features=["small_rng"] }
